apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: app-prod
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    max_connections=500
    innodb_buffer_pool_size=256M
    innodb_log_file_size=64M
    slow_query_log=1
