apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: app-prod
spec:
  replicas: 4

  selector:
    matchLabels:
      app: nodejs

  template:
    metadata:
      labels:
        app: nodejs

    spec:
      containers:
      - name: nodejs

        image: rutik141/my-nodejs-app:10

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: DB_NAME

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: PORT

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 20
          periodSeconds: 10
