apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app-prod
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: appdb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass123
